@cookie = rs-auth=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzZWpAb3V0bG9vay5jb20iLCJyb2xlcyI6IlUgQSBFIiwiZXhwIjoxNjY4NDgxNzI2fQ.d46NdKkl-AL7BpsCubMdSy-SwK_MloBcD5_c8l5MLSmtyv_wl_cpHgRcN3iXUeTXxx9KeivU9BSslyZNoJbdiA

GET http://localhost:3100/rs-data/?$list=nodirs,recursive

###

GET http://localhost:3100/rs-data/posts/.schema.json

###

GET http://localhost:3100/rs-data/posts/2021-08-12.json

###

GET http://localhost:3100/admin/?$list=recursive,all,nodirs
X-Restspace-Request-Mode: manage

###
GET http://localhost:3100/user-bypass/jamesej@outlook.com?$fragment=roles

### Login
POST http://localhost:3100/auth/login
Content-Type: application/json

{
	"email": "jamesej@outlook.com",
	"password": "hell4ire"
}

###
GET http://localhost:3100/.well-known/restspace/services?$fragment=/data/ds

###
GET http://localhost:3100/.well-known/restspace/catalogue

###
OPTIONS https://restspace.local:3131/?$list=details
Origin: https://restspace.local:3003

###
GET https://restspace.local:3131/files/?$filter=/lib/selector-schema

###
POST https://restspace.local:3131/templates/test
Content-Type: application/json

{
	"abc": 123
}

###
GET https://restspace.local:3131/test-abc

###
POST https://restspace.local:3131/pdf
Content-Type: text/html

<html>
	<body>
		<div>Hello</div>
	</body>
</html>

###
POST https://restspace.local:3131/email?to=jamesej@outlook.com&subject=Test1&content=Attached+body
Content-Type: application/zip

< C:\dev\XOTIC_PRO64_C++.zip

###
GET https://restspace.local:3131/aws/rs-common/?list-type=2

###
GET http://restspace.local:3100/discord/command/950463239186165760/?$list=details

###
GET http://restspace.local:3100/discord/command/950463239186165760/.schema.json

###
GET https://discord.com/api/v8/applications/950706166017695754/guilds/950463239186165760/commands
Authorization: Bot <token>
User-Agent: DiscordBot (https://restspace.io, 0.1)

###
GET https://discord.com/api/v8/guilds/950463239186165760/channels
Authorization: Bot
User-Agent: DiscordBot (https://restspace.io, 0.1)

###
GET http://restspace.local:3100/discord/command/950463239186165760/do-stuff%7C953576078503452692

###
GET https://apis.restspace.io/templates/home

###
GET http://restspace.local:3100/tempac/733273a6-8c31-45c0-8d98-4037ba475dac/files/telephone.svg

###
GET http://restspace.local:3100/files/telephone.svg


###
GET http://restspace.local:3100/files/telephone.svg

###
POST http://restspace.local:3100/pipelines/test-b64?$to-step=0

###
POST http://restspace.local:3100/lib/to-b64
Content-Type: application/pdf

hello

###

https://restspace.local:3131/files/tulips.png

###
https://ademchic2.restspace.io/project-list

###
POST https://localhost:9200/customer/_doc/1
Content-Type: application/json
Authorization: Basic elastic 1RdRylip2LfwsWpkJWto

{
	"firstname": "Jennifer",
	"lastname": "Walters"
}
###
POST https://localhost:9200/_search
Content-Type: application/json
Authorization: Basic elastic 1RdRylip2LfwsWpkJWto

{
	"query": {
		"match_all": {}
	}
}

###
DELETE https://localhost:9200/customer/_doc/3.json
Content-Type: application/json
Authorization: Basic elastic 1RdRylip2LfwsWpkJWto

###
GET https://localhost:9200/testac/_search
Content-Type: application/json
Authorization: Basic elastic 1RdRylip2LfwsWpkJWto

{
	"query": {
		"multi_match": {
			"query": "door red",
			"type": "bool_prefix",
			"fields": [
				"search",
				"search._2gram",
				"serach._3gram"
			]
		}
	}
}

###
POST https://restspace.local:3131/query/test
Content-Type: application/json

{
	"subgroup": "6"
}

###
POST https://restspace.local:3131/query/multitest
Content-Type: application/json

{
	"subgroups": [ "5", "6" ]
}

###
GET https://restspace.local:3131/data/ds-auth/abc

###
GET https://restspace.local:3131/ds-auth-access/abc

###
POST https://ademchic2.restspace.io/backend/catitem-data/plumbing/taps/Matt black tap

###
POST https://ademchic2.restspace.io/query/filteredAutocomplete/1/2/ach

###
PATCH https://restspace.local:3131/data/es/test/one
Content-Type: application/json

{
	"b": "goodbye"
}

###
GET https://restspace.local:3131/data/es/test/two.json

###
POST https://ademchic2.restspace.io/query/autocomplete/ta

###
POST https://restspace.local:3131/csv/ndjson
Content-Type: text/csv

< D:\Dev\ademchic-assets\catalogue.csv

###
POST https://ademchic2.restspace.io/catalogue-converter/ndjson
Content-Type: text/csv

< D:\Dev\ademchic-assets\catalogue.csv

###
POST https://ademchic2.restspace.io/catalogue-converter/json
Content-Type: text/csv

,P1,P-1,Paint,Wall Paint,Pure Brilliant White Matt Finish,S 0500-N,Pure Brilliant White,Matt finish ,,,Dulux,Contractor to quote,https://www.dulux.co.uk/en/colour-details/pure-brilliant-white,,,,,,,,,,,,,,,,,

###
GET https://restspace.local:3131/log/json/100

###
POST https://ademchic2.restspace.io/backend/itemsById
Content-Type: application/json
Cookie: {{cookie}}

{
	"ids": [
		"d2189420-6537-41fa-a856-9be8bf3fa7fa",
		"80bd4047-72e3-45f4-a7ea-f694e924080c",
		"d486c7d2-02d2-4364-aee2-8334732138f6",
		"466ddcd1-dfd8-40a1-8d2a-97470363c3bd",
		"41de67ef-5ff9-4874-8c03-750773540c70",
		"a074c1e2-a767-4de2-a9a8-af96544edbcf",
		"344a629b-ef81-47d6-a674-e204d1bae411",
		"8bddf31c-062d-4bd2-8677-5c236e7b4c39",
		"a6df2ade-c019-446d-878d-6310de152a29",
		"ade11357-3211-4f7c-8f7e-ac3156e6fb89",
		"ecd53a0f-3969-446c-a233-e91e91d6e447",
		"8ff65262-ebc6-49b2-9cf0-f868d509d31f",
		"f9c0a6c5-5fc2-4462-ad8c-9f6cbbfed71b"
		]
}

###
POST https://ademchic2.restspace.io/query/all

###
GET https://ademchic2.restspace.io/log/json/30
Cookie: {{cookie}}

###
POST https://ademchic2.restspace.io/elastic/catalogue/_search
Content-Type: application/json

{
	"size": 1000,
	"query": {
		"match_all": {}
	},
	"fields": [
		"_id", "_timestamp"
	],
	"_source": false
}

###
DELETE https://ademchic2.restspace.io/elastic/catalogue2

###
GET https://restspace.local:3131/css/test

###
GET https://restspace.local:3131/files/item_/aFile/IMG-20220803-WA0008.jpg

###
POST https://ademchic2.restspace.io/new-pdf
Content-Type: application/json
Cookie: {{cookie}}

{
	"data": "<html><head></head><body><div style=\"background-image: url('https://ademchic2.restspace.io/file/image/json/instance/reportgen/index.json/frontpage/coverimage/cover-image.jpg'); width: 200px; height: 200px; background-size: cover\"></div></body></html>",
	"format": "A4",
	"landscape": true,
	"persisted": true,
	"s3Bucket": "rs-pdf-output",
	"s3Key": "pdf-b",
	"printBackground": true
}

###
GET https://ademchic2.restspace.io/template/
Cookie: {{cookie}}

###
POST https://ademchic2.restspace.io/backend/transfer?from=/&to=ademchic3.restspace.io/
Content-Type: application/json
X-Restspace-Request-Mode: manage
Cookie: {{cookie}}

###

GET https://ademchic2.restspace.io/cat/?$list=recursive
Content-Type: application/json
X-Restspace-Request-Mode: manage
Cookie: {{cookie}}

###

GET https://sourcify.dev/server/repository/contracts/full_match/1/0xca2ad74003502af6B727e846Fab40D6cb8Da0035/metadata.json

###

GET https://deno.land/std@0.185.0/log/mod.ts?source

###

GET https://lib.restspace.io/core/Message.ts

###

GET https://restspace.local:3131/services/abc.ts

###

POST https://restspace.local:3131/pipelines/change-role

###
GET https://lib.restspace.io/.well-known/restspace/services

###
GET https://restspace.local:3131/.well-known/restspace/catalogue

###

POST https://restspace.local:3131/embeddings
Content-Type: text/plain

function f(x) {
	return x * x;
}
###
POST https://restspace.local:3131/sns/
Content-Type: application/x-www-form-urlencoded

PhoneNumber=+447719792965&Message=Hello+World&Action=Publish&Version=2010-03-31
