@cookie = rs-auth=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzZWpAb3V0bG9vay5jb20iLCJyb2xlcyI6IlUgQSBFIiwiZXhwIjoxNjQyNzU4NzI3fQ.uHOJRtIGYJNVihuiys8MuTGloUSEBR4aQwVPLqejLxCPtKbwIdJ4RW0ve6rDBGM7d20cySdpqDSyCPppiNQE2A

GET http://localhost:3100/rs-data/?$list=nodirs,recursive

###

GET http://localhost:3100/rs-data/posts/.schema.json

###

GET http://localhost:3100/rs-data/posts/2021-08-12.json

###

GET http://localhost:3100/admin/?$list=recursive,all,nodirs
X-Restspace-Request-Mode: manage

###
GET http://localhost:3100/user-bypass/jamesej@outlook.com?$fragment=roles

### Login
POST http://localhost:3100/auth/login
Content-Type: application/json

{
	"email": "jamesej@outlook.com",
	"password": "hell4ire"
}

###
GET http://localhost:3100/.well-known/restspace/services?$fragment=/data/ds

###
GET http://localhost:3100/.well-known/restspace/catalogue

###
OPTIONS https://restspace.local:3131/?$list=details
Origin: https://restspace.local:3003

###
GET https://restspace.local:3131/files/?$filter=/lib/selector-schema

###
POST https://restspace.local:3131/templates/test
Content-Type: application/json

{
	"abc": 123
}

###
GET https://restspace.local:3131/test-abc

###
POST https://restspace.local:3131/pdf
Content-Type: text/html

<html>
	<body>
		<div>Hello</div>
	</body>
</html>

###
POST https://restspace.local:3131/email?to=jamesej@outlook.com&subject=Test1&content=Attached+body
Content-Type: application/zip

< C:\dev\XOTIC_PRO64_C++.zip

###
GET https://restspace.local:3131/aws/rs-common/?list-type=2

###
GET http://restspace.local:3100/discord/command/950463239186165760/?$list=details

###
GET http://restspace.local:3100/discord/command/950463239186165760/.schema.json

###
GET https://discord.com/api/v8/applications/950706166017695754/guilds/950463239186165760/commands
Authorization: Bot <token>
User-Agent: DiscordBot (https://restspace.io, 0.1)

###
GET https://discord.com/api/v8/guilds/950463239186165760/channels
Authorization: Bot
User-Agent: DiscordBot (https://restspace.io, 0.1)

###
GET http://restspace.local:3100/discord/command/950463239186165760/do-stuff%7C953576078503452692

###
GET https://apis.restspace.io/templates/home

###
GET http://restspace.local:3100/tempac/733273a6-8c31-45c0-8d98-4037ba475dac/files/telephone.svg

###
GET http://restspace.local:3100/files/telephone.svg


###
GET http://restspace.local:3100/files/telephone.svg

###
POST http://restspace.local:3100/pipelines/test-b64?$to-step=0

###
POST http://restspace.local:3100/lib/to-b64
Content-Type: application/pdf

hello

###

https://restspace.local:3131/files/tulips.png

###
https://ademchic2.restspace.io/project-list

###
POST https://localhost:9200/customer/_doc/1
Content-Type: application/json
Authorization: Basic elastic 1RdRylip2LfwsWpkJWto

{
	"firstname": "Jennifer",
	"lastname": "Walters"
}
###
POST https://localhost:9200/_search
Content-Type: application/json
Authorization: Basic elastic 1RdRylip2LfwsWpkJWto

{
	"query": {
		"match_all": {}
	}
}

###
DELETE https://localhost:9200/customer/_doc/3.json
Content-Type: application/json
Authorization: Basic elastic 1RdRylip2LfwsWpkJWto

###
GET https://localhost:9200/testac/_search
Content-Type: application/json
Authorization: Basic elastic 1RdRylip2LfwsWpkJWto

{
	"query": {
		"multi_match": {
			"query": "door red",
			"type": "bool_prefix",
			"fields": [
				"search",
				"search._2gram",
				"serach._3gram"
			]
		}
	}
}

###
POST https://restspace.local:3131/query/test
Content-Type: application/json

{
	"subgroup": "6"
}

###
GET https://restspace.local:3131/test-pipeline

###
POST https://ademchic2.restspace.io/backend/catitem-data/plumbing/taps/Matt black tap

###
POST https://ademchic2.restspace.io/query/filteredAutocomplete/1/2/ach

###
PATCH https://restspace.local:3131/data/es/test/one
Content-Type: application/json

{
	"b": "goodbye"
}

###
GET https://restspace.local:3131/data/es/test/two.json

###
POST https://ademchic2.restspace.io/query/autocomplete/ta

###
POST https://restspace.local:3131/csv/ndjson
Content-Type: text/csv

hello, 1, true
hello2, 4, false